---
templates:
  tv:

    manipulate:
      - title: &the
          replace:
          regexp: '^The\W'
          format: ''
      - filename: *the
      - series_name: *the

    private_torrents: no

    series:
      settings:
        tv:
          exact: yes
          propers: 3 days
          quality: 720p+
          set:
            path: /mnt/plex_vol/media/{{series_name}}
      tv:
        - Archer
        - Beavis and Butt-head
        - Big Band Theory
        - Breaking Bad
        - Dexter
        - Fringe
        - Game of Thrones
        - Mad Men
        - MythBusters
        - The Office
        - Real Time with Bill Maher
        - South Park
        - True Blood

    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: transmission
      password: lol12345
      removewhendone: no

tasks:
  bt-chat.com-tv:
    priority: 1
    rss: http://rss.bt-chat.com/?group=3
    template: tv

  ezrss.it:
    priority: 2
    rss: http://ezrss.it/feed/
    template: tv

  thepiratebay.org-tv:
    priority: 3
    rss: http://rss.thepiratebay.org/208
    template: tv
    verify_ssl_certificates: no

  kat.ph-tv:
    priority: 4
    rss: http://kat.ph/tv/?rss=1
    template: tv

  extratorrent.com-tv:
    priority: 5
    rss: http://extratorrent.com/rss.xml?cid=8
    template: tv

  torrentz.eu-tv:
    priority: 6
    rss: http://torrentz.eu/feed
    template: tv

  showrss.karmorra.info-tv:
    priority: 7
    rss: http://showrss.karmorra.info/feeds/all.rss
    template: tv