variables: variables.yml

web_server:
  web_ui: yes
  bind: 0.0.0.0
  port: 3550
  base_url: /flexget

templates:

  global:
    no_entries_ok: yes

  anchors:
    _transmission: &transmission
      host: '{? transmission.host ?}'
      port: '{? transmission.port ?}'
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'

    _filesystem: &filesystem
      retrieve: files
      regexp: '.*\.(mp4|mkv|mp4|mov|mpg|mpeg|avi)$'

    _trakt_list: &trakt_list
      username: '{? trakt.username ?}'
      account: '{? trakt.username ?}'
      strip_dates: yes

tasks:

  download-anime:
    rss:
      url: '{? feeds.anime ?}'
      all_entries: no
    imdb_lookup: yes
    require_field: imdb_id
    transmission:
      <<: *transmission
      content_filename: "{{series_name}} {{series_id|pad(2)}}"
      path: '{? transmission.downloads ?}/anime/'

  download-tv:
    rss:
      url: '{? feeds.tv ?}'
      all_entries: no
      silent: yes
      escape: yes
    imdb_lookup: yes
    require_field: imdb_id
    transmission:
      <<: *transmission
      path: '{? transmission.downloads ?}/.tv/'
  
  download-movies:
    rss:
      url: '{? feeds.movies ?}'
      all_entries: no
    imdb_lookup: yes
    require_field: imdb_id
    list_match:
      from:
        - movie_list: movies
    transmission:
      <<: *transmission
      path: '{? transmission.downloads ?}/.movies/'

  update-movie-list:
    limit:
      amount: 10
      from:
        trakt_list:
          <<: *trakt_list
          list: '{? trakt.movies ?}'
          type: movies
    accept_all: yes
    imdb_lookup: yes
    list_add:
      - movie_list: movies
    list_remove:
      - trakt_list:
          <<: *trakt_list
          list: '{? trakt.movies ?}'
          type: movies

  sort-anime:
    filesystem:
      <<: *filesystem
      path: '{? local.downloads ?}/anime/'
    accept_all: yes
    disable: builtins
    move:
      to: "{? local.videos ?}/Anime/{{title|re_replace(' \\d{2}','')|replace('.mkv','')}}/"
  
  sort-tv:
    filesystem:
      <<: *filesystem
      path: '{? local.downloads ?}/tv/'
    metainfo_series: yes
    accept_all: yes
    disable: builtins
    move:
      to: "{? local.videos ?}/tv/{{series_name}}/Season {{series_season}}/"
      rename: "{{series_name|replace(':',' -')}} {{series_id|pad(2)}}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}"

  move-movies:
    filesystem: 
      <<: *filesystem
      path: '{? local.downloads ?}/.movies/'
    accept_all: yes
    tmdb_lookup: yes
    disable: builtins
    move:
      to: "{? local.videos ?}/movies/"
      rename: "{{tmdb_name|replace(':',' -')}} [{{tmdb_year}}]"
  
schedules:
  - tasks: [ download-anime, download-tv, sort-* ]
    schedule:
      minute: "*/15"
  - tasks: [ update-movie-list, download-movies, move-movies ]
    schedule:
      hour: "*/6"
      minute: 10,40