---
## File: roles/flexget/tasks/main.yml
## Purpose: Executes the tasks for the flexget role

#####################################################################################
## Install Plex
#####################################################################################
- name: Start Plex Container
  community.docker.docker_container:
    name: plex
    image: lscr.io/linuxserver/plex:latest
    state: started
    restart: yes
    network_mode: host
    container_default_behavior: no_defaults
    env:
      TZ: "Australia/Melbourne"
      VERSION: "docker"
      PLEX_CLAIM: "claim-eikSZAggTSAyQzed69Gt"
      ALLOWED_HOSTS: "0.0.0.0/0"
    volumes:
      - /mnt/plex_vol/config/:/config
      - /mnt/plex_vol/media/:/downloads
      - /mnt/plex_vol/transcode/:/transcodes
  tags:
  - launch_plex