---
## File: roles/flexget/tasks/main.yml
## Purpose: Executes the tasks for the flexget role

#####################################################################################
## Install Plex
#####################################################################################
- name: Create Plex Config directory
  ansible.builtin.file:
    path: /mnt/plex_vol/config/
    state: directory
    owner: debian-transmission
    group: debian-transmission
    mode: '0755'
  tags:
  - launch_plex
  
- name: Create Plex Transcodes directory
  ansible.builtin.file:
    path: /mnt/plex_vol/transcode/
    state: directory
    owner: debian-transmission
    group: debian-transmission
    mode: '0755'
  tags:
  - launch_plex

- name: Start Plex Container
  community.docker.docker_container:
    name: plex
    image: lscr.io/linuxserver/plex:latest
    state: started
    restart: yes
    network_mode: host
    env:
      TZ: "Australia/Melbourne"
      VERSION: "docker"
      PLEX_CLAIM: "claim-vcvqeeFr5D1AK1yqUbEm"
      ALLOWED_HOSTS: "0.0.0.0/0"
    volumes:
      /mnt/plex_vol/config/:/config:rw
      /mnt/plex_vol/media/:/data:rw
      /mnt/plex_vol/transcode/:/transcode:rw
  tags:
  - launch_plex